luxtronik/datatypes.py
If IP addresses are below 128.0.0.0 the corresponding integer value is not below 0, so adding 2 **32  to the value results in illegal values and the reading of values crashes
=> fix issue with ip4 addresses below 128.0.0.0

luxtronik/__init__.py, luxtronik/calculations.py, luxtronik/parameters.py, luxtronik/visibilities.py
Having `logging.basicConfig()` in a library will break ones own config if the library is imported before owns config.
=> Remove logging config as it breaks projects one

.github/workflows/pylint.yml, luxtronik/__init__.py, luxtronik/parameters.py, setup.py
This adds a GitHub action that will lint all Python files with pylint. This will ensure that the code will be more consistent when multiple persons are working on it. Also it will warn us about potential issues.
In case we don't like specific rules, the linter can be disabled for specific files and code sections and also re-configured. The output is verbose and solutions to reported issues can typically be easily found by searching the Internet (TM).
=> Add pylint as GitHub action to increase code quality and consistency

luxtronik/datatypes.py, luxtronik/parameters.py
This adds full support for parameter `107`. This parameter is used internally
to define the access level to all kind of additional data that is not available
for typical users.
The access level can be changed locally by entering special codes, which are
well known among most advanced users:
- `9445` -> `installer`
- `7113` -> `after sales service`
There is an additional mode that can be enabled by inserting a specially
crafted USB stick into the USB interface of the controller. This will
grant the user `manufacturer` access level.
In the end, though, these hurdles are all falling back to using parameter `107`
to define the access value.
Therefore the current access level can be read from this parameter and be
translated into a string via the `AccessLevel` datatype.
Additionally the …
=> Add support for access level parameter

.github/workflows/lint.yml, .github/workflows/publish-to-pypi.yml, .github/workflows/pylint.yml, .markdownlint.yml, .yamllint.yml, LICENCE.md, README.md
This implements linting for Markdown and YAML files within the repository as GitHub actions. Upon pushing the linters will be triggered, checking if there are any issues with the file formats.
This ensures more consistency and quality throughout the project.
The linters that are being used are:
- yamllint: https://github.com/adrienverge/yamllint
- markdownlint: https://github.com/DavidAnson/markdownlint
Some minor issues have already been identified with the existing files. Those are also being addressed with this pull request in order to make (and hopefully keep) the linters happy.
In addition to that there are configuration files (`.yamllint.yml` and `.markdownlint.yml`) that can be used to fine-tune the linters.
=> Add source file linting for Markdown and YAML files

.github/workflows/lint.yml
This fixes a deprecation warning in the output of the `pylint` job:
```
Warning: The `set-output` command is deprecated and will be disabled
soon. Please upgrade to using Environment Files. For more information
see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
See [1] for more details.
Since this will become a more serious issue later this year, it needs to be addressed. It can be easily fixed by using `v4` of the `setup-python` GitHub action.
This fixes issue #51.
[1]: https://github.com/Bouni/python-luxtronik/actions/runs/3929482958/jobs/6718345175
=> Fix deprecation warning in workflow

luxtronik/datatypes.py
This updates code 3 of the `BivalenceLevel` datatype. This value indicates that additional heat sources may be used. It is NOT about the compressor.
Refer to the operating manual for details. It can be found in English [here](https://s3p.manualzz.com/store/data/054697098.pdf?key=d3cc293e6bcdaee2d95d71716f830bfb&r=1&fn=54697098.pdf&t=1673905309047&p=86400).
The relevant aspect of the manual describes it like this:
=> Update code 3 of BivalenceLevel datatype

luxtronik/datatypes.py
This is a small change to the Kelvin datatype to make it consistent with the Celsius datatype, since they were inconsistent previously.
This will allow us to refactor the code later on more easily (e.g. have some kind of temperature super class, etc.).
This addresses and closes #58.
=> Make Kelvin datatype consistent to Celsius

luxtronik/datatypes.py
Replace the use of the `ipaddress` module combined with unclear addition subtraction in favor of `socket` and `struct`.
=> Improve handling of IP addresses

.github/workflows/lint.yml, luxtronik/__init__.py, pyproject.toml
This morning I heared the Epsiode 400 of the [Talk Python Podcast](https://talkpython.fm/episodes/show/400/ruff-the-fast-rust-based-python-linter) in which they spoke about `ruff` a new linter written in Rust that  10-110 times faster than other liters.
So I thought wh not use it instead of pylint which is the slowest in their comparison:
=> Replace pylint with ruff in GH Actions

README.md, scripts/dump-luxtronik.py
This adds a script that will allow users to dump all known values from
the Luxtronik controller, including:
- parameters
- calculations
- visibilities
The script itself was taken from a [Gist][gist].
In addition to that a few changes have been made:
- Changes to code to stay compliant with `pylint`
- Implementation of argument parsing via `argparse`
This change closes https://github.com/Bouni/python-luxtronik/issues/59.
[gist]: https://gist.github.com/Bouni/cf0dc2c7c53c32deeb264803ec350e5c
=> Add script to dump all values from Luxtronik controller

.github/workflows/lint.yml, .github/workflows/pytest.yml, tests/test_datatypes.py
This implements some basic unit tests. Having unit tests is considered to be good practice and allows us to refactor the code while reducing the risk for regressions and silly mistakes. The test suites are based on `pytest`, which is the de-facto standard for unit tests in Python.
The pull request consists of multiple changes / commits:
- Implementation of actual unit tests in `tests/test_datatypes.py`. This is a first basic test suite for the `datatype` module. It is not covering every edge case, and is more of a starting point that can be used to elaborate later on. Other modules also need to have unit tests implemented, which will follow in additional pull requests later on.
- Implementation of `pytest` as GitHub action: This will run the test suites automatically whenever new code is …
=> Implement unit testing for datatypes module

.github/workflows/lint.yml, .github/workflows/pytest.yml
As discussed in #77 I've added `black` to the lint CI job.
Info: https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#writeback-and-reporting
=> Add black in RO mode to lint GH action

pyproject.toml
I realized that the PR #86  does fail because of pylint, so I added some sane pylint configs to pyproject.toml
=> Add more linter rules

luxtronik/datatypes.py
As demonstrated in #89 the value 19 for the SwitchoffFile datatype represents `PV max`.
This change adds the entry accordingly to make the mapping available for consumers of the datatype module.
Fixes #89.
=> Add mapping for PV max to SwitchoffFile datatype

.github/workflows/lint.yml
The "black" workflow only states that some files should be changed, but does not report these changes.
Fixed this by adding a --diff option to the call.
Fixes #93
=> issue-93: Also output the suggested changes of the 'black' workflow

tests/test_datatypes.py
Unfortunately, in #90 the test_datatypes.py was forgotten to adapt to the changes. Fixes #89.
=> issue-85: Increased the expected count of switchofffile options within the test_datatypes.py

luxtronik/calculations.py, luxtronik/datatypes.py, luxtronik/parameters.py, luxtronik/visibilities.py, scripts/dump-changes.py, scripts/dump-luxtronik.py
If the selection value is unknown, output the raw value instead of None to simplify the "reverse engineering".
fixes #91 
Update:
Summary of the changes:
- The data field class `Base` now stores the raw value instead of the already converted "user value"
- Added a property `Base.Raw` to set and get the stored raw value directly
- Added a property `Base.Value` to get the stored raw value converted tothe "user value"
- Added a property `Base.Value` to set the stored value by a "user value" which is converted to raw data
- The string representation `Base.__str__` now output the raw value if the "user value" is None
- The script `dump-luxtronik.py` now uses the string representation of the data field class
=> issue-91: Return the raw value instead of "None" in the __str__ method of the data fields

README.md, luxtronik/datatypes.py, tests/test_datatypes.py
As discussed in #49 the implementation of the functions `Base.to_heatpump`, `Base.from_heatpump` and `SelectionBase.options` are correspond to class methods. But are not yet offered as such.  This pull-request transform them into class-methods.
=> issue-49: Convert some datatype functions into class methods

tests/test_datatypes.py
This addresses issuees with the unit tests of SelectionBase, as they have not been working since the usage of class methods. In order to fix those unit tests a new child class of SelectionBase is required, which sets some codes that are then being evaluated by the test methods, since any class methods don't have access to codes that are being set on a per-instance level.
=> Fix unit tests for SelectionBase

tests/test_datatypes.py
This adjusts test cases for datatypes in such a way that the recently introduced class methods are invoked on the class rather than on an class instances.
=> tests: Don't invoke class methods on class instances

.github/workflows/pytest.yml
This enables the pipefail option as part of the pytest invocation in order to not suppress errors detected by pytest due to the piping into `tee` afterwards.
This addresses and closes #104.
=> pytest: Enable pipefail

luxtronik/calculations.py, luxtronik/datatypes.py, tests/test_datatypes.py
This introduced a new datatype (`MajorMinorVersion`) that is used to interpret calculation 258. It has been reported (see #99) that this calculation is used to encode the version information from the "Raumbedieneinheit" (RBE).
For me this value is 0 (don't have this hardware), for the reporter of #99 it is `112`, which is being shown as `1.12` in the web interface.
The pull request also contains test cases that cover the currently known values.
=> Introduce datatype MajorMinorVersion to handle calculation 258

.pre-commit-config.yaml
In order to get a consistent quality of our README.md (and probably other Markdown files to come) we should add markdownlint to our pre-commit-hooks.  
Yamllint was added to ensure the .pre-commit-hooks.yaml is formated correctly as well.
=> Add yamllint and markdownlint to pre-commit-hooks

luxtronik/calculations.py, luxtronik/datatypes.py, tests/test_datatypes.py
This works towards #122.
In `calculations.py` we have an exceptional handling for the fields 81-90, since these ten fields contain the version information. Positions 82-90 were uninhabited; with this patch, a new `VersionChild` sits there and gobbles the value for its parent.
A new flag `datatype_internal` indicates, that this datatype is only internal and the iterator of `Calculations` will skip this entry.
=> Create a VersionChild datatype

.github/workflows/lint.yml, .github/workflows/pytest.yml
This is an attempt to prevent our CI pipeline from running twice for every PR.
There is no need to run it `on: push` for a PR and `on: pull-request` as well.
=> Attempt to run CI only once

luxtronik/calculations.py, luxtronik/data_vector.py, luxtronik/parameters.py, luxtronik/visibilities.py, tests/test_calculations.py, tests/test_parameters.py, tests/test_visibilities.py
This patch addresses #122. It also provides some simple tests for these classes.
Please let me know if you have a better name for the base class.
=> Common base class for Parameters,Calculations,Visibilities

luxtronik/datatypes.py
`int(some_float)` always rounds towards zero and this is (maybe) not what is expected.
This PR suggests to replace `int()` by `round()`.
=> Use round instead of int in `datatypes.py`

luxtronik/__init__.py
Using a decorator we can simply re-use the code to connect to the heat pump. This allows us to offers several read / write functions like only read the paramters.
Fixes #130
=> Added a decorator to connect to the heat pump

luxtronik/calculations.py
As discovered by @RobinFlikkema in #143 the calculation 267 shows up in the webinterface as desired room temperature.
=> Add calculation 267 as desired room temperature

.github/workflows/pytest.yml
This is an attempt to fix the pytest issue surfaced in #151
=> Try traget pull_request instead of pull_request_target

.github/workflows/pytest.yml
I hope this fixes the last issue in #151
=> Add write permissions for coverage on pull requests

.github/workflows/pytest.yml
Next attempt, this time I try what Chat GPT thinks is the right way of doing this
=> Fix coverage

.github/workflows/coverage.yml, .github/workflows/pytest.yml
This is a two staged approach to fix the permission problme when posting the coverage report on a PR that fomes from a forked repo.
Found here:
- https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
- https://github.com/MishaKav/pytest-coverage-comment/issues/68#issuecomment-1836219787
=> Two staged coverage comment attempt

.github/workflows/coverage.yml
`workflows:`must contain the `name` of the other workflow, not the filename
=> Fix workflow_run name

.github/workflows/coverage.yml, .github/workflows/pytest.yml
I finally fixed the coverage comment issue 🥳 
1. It is necessary to have a two staged solution because of security reasons, details can be found in GitHubs blog post: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
2. MishaKav/pytest-coverage-comment did not allow the `workflow_run` trigger which prevented the coverage report to be posted. I forked the repo, fixed the issue and opend https://github.com/MishaKav/pytest-coverage-comment/pull/153 . Until that PR is merged we can use my fork `bouni/pytest-coverage-comment@workflow_run`
=> Fix coverage comment

.github/workflows/coverage.yml
My PR to [MishaKav/pytest-coverage-comment](https://github.com/MishaKav/pytest-coverage-comment/) has been merged and therefore we can revert back to the original action
Details see here: https://github.com/MishaKav/pytest-coverage-comment/pull/153#issuecomment-1940509467
=> Revert action to MishaKav/pytest-coverage-comment@main

README.md, luxtronik/__init__.py, luxtronik/scripts/dump_changes.py, luxtronik/scripts/dump_luxtronik.py
With #86 we split the data from the read/write interface.
However, these changes mean that the existing program needs to be adjusted.
With this pull-request we restore the previous api by:
- Add a data class that contains the parameters, calculations and visibilities
- Keep the seperation of the data class and the read/write interface
- Provide a new "Luxtronik" class that combines the data and the interface
This allows both the old and the new API to be used.
Fix #132 
NOTE: The linter added some format changes.
=> Issue-132: Revert API changes introduces with #86

luxtronik/__init__.py, tests/test_socket_interaction.py
This provides almost 100% coverage of `__init__.py`. I am not sure about the missing lines. Sockets are weird, in particular checking whether a socket is closed / no longer usable.
Also the `struct.error` is not sensible in my opinion, but this should be discussed elsewhere.
*Edit:* And with the tests, I found a typo :)
=> Test the socket interaction by mocking the socket

luxtronik/__init__.py
Sometimes `self._socket.recv` returns fewer bytes than requested (for me, this happens sometimes over VPN). The current `try-check` in `read_*` is not helpful, since it just skews up the readings, e.g., if we only get 2 bytes for parameter 1, the remaining 2 bytes are then feed into parameter 2 and so on...
The current fix assures that the correct amount of bytes is read by introducing a new function `_read_bytes()`.
=> Fix reading from socket

.github/workflows/lint.yml, .pre-commit-config.yaml, tests/test_socket_interaction.py
I noticed that ruff was complaining after I merged a PR that was open for a few months, despite it was marked as all good in the PR view.
Probably som versin mismatch or something like that. 
So I fixed the linter warnings and upgraded the pre-commit-cofig and the lint action.
=> Fix ruff issues

.github/workflows/lint.yml, .github/workflows/publish-to-pypi.yml
I noticed this message in the Annotation section of the markdownlint and yamllint actions:
> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, actions/setup-node@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
So I upgraded all actions versions that have new versions available
=> Upgrade actions

README.md
Add instructions on how to install via pip from the git repo.
=> Add more intallation instructions

luxtronik/discover.py, tests/test_discover.py
As brought up in #73 the discover function was to large and cased ruff warnings.
This PR splits the discover function into smaller logical functions and adds unit tests
=> Refactor discover function
